apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-app
spec:
  replicas: 2
  selector:
    matchLabels: { app: trend }
  template:
    metadata:
      labels: { app: trend }
    spec:
      containers:
      - name: trend
        image: priyadharshini030722/trend:latest
        ports: [{ containerPort: 3000 }]
        readinessProbe:
          httpGet: { path: "/", port: 3000 }
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: "/", port: 3000 }
          initialDelaySeconds: 30
          periodSeconds: 20
