apiVersion: v1
kind: Service
metadata:
  name: trend-app
  namespace: default
  labels:
    app: trend
spec:
  type: LoadBalancer
  selector:
    app: trend
  ports:
    - protocol: TCP
      port: 80         # Port exposed via LoadBalancer
      targetPort: 3000 # Port on your pods
